Add challenges
unikraft-upb/USoC23-registration pull request #1
Opened 2023-04-13 14:04 UTC by StefanJum

2023-04-13 14:10 UTC, craciunoiuc commented
The challenges look good, I'll have to also try them out, but the difficulty seems fine.

2023-04-13 14:31 UTC, craciunoiuc commented
Considering the target audience, I would not call the second task `simple`, but there must be something to set people apart.
Or maybe I just misinterpreted the challenge.

The first and third challenge are good though.

2023-04-13 14:49 UTC, StefanJum commented
> Considering the target audience, I would not call the second task `simple`, but there must be something to set people apart. Or maybe I just misinterpreted the challenge.
> 
> The first and third challenge are good though.

Makes sense. I can move it to no. 3 just to not hit the people trying too soon.
The challenge can be solved with `strings` or `ltrace` (it waits for a password, does a `strcmp` and then prints the flag), maybe I can make it more verbose, by adding some input prompts (e.g. `Enter the password:`) so it's clear for everyone what they should do.

I can also remove or replace it, I could not come up with an easier idea that would not be just too easy and I thought that leaving only the other 2 is a little too less work, but if this one is too difficult we can leave it out.

2023-04-13 14:54 UTC, craciunoiuc commented
Ah whoops, okay. I tried gdb-ing inside it but for some reason it didn't work and then I saw the key and I thought they had to overwrite the strcmp bytes with nop operations 😅

2023-04-13 15:08 UTC, StefanJum commented
> Okay then you can leave it like this, but maybe hint that the password is already in the binary.

Yes, I'll do that.

2023-04-13 20:44 UTC, RaduNichita requested changes
Looking awesome, nice work @StefanJum !

I left a few nitpicks and little suggestions.

2023-04-13 20:44 UTC, RaduNichita commented on 01-build-system/src/main.c
> +extern char* traveler;
```suggestion
extern char *traveler;
```

2023-04-13 20:44 UTC, RaduNichita commented on 01-build-system/README.md
> +You are asked to create a `Makefile` that will be used to build everything into an executable file.
```suggestion
Your task is to create a `Makefile` that will be used to build everything into an executable file.
```

2023-04-13 20:44 UTC, RaduNichita commented on 01-build-system/README.md
> +Copy that flag and paste it in the [registration form](TODO), along with the `Makefile` you created.
Maybe they should create a zip archive in which they will upload multiple files?

2023-04-13 20:44 UTC, RaduNichita commented on 01-build-system/src/main.c
> +int main(int argc, char *argv[])
```suggestion
int main(void)
```

2023-04-13 20:44 UTC, RaduNichita commented on 03-my-first-unikernel/README.md
> +You are given a unikernel image.
Maybe put a link / add a short description about  what is a unikernel image?

2023-04-13 20:44 UTC, RaduNichita commented on 03-my-first-unikernel/README.md
> +$ your-run-command
```suggestion
$ <your_run_command>
```

2023-05-19 14:16 UTC, StefanJum commented
The challenges were published in the main [unikraft docs repository](https://github.com/unikraft/docs/tree/main/content/en/community/hackathons/sessions/registration-challenges)

2023-05-19 14:16 UTC, closed without merging